name: story_view
description: Display stories just like Whatsapp & Instagram. Can be used inline/inside ListView or Column just like Google News app. Comes with gestures to pause, forward & go to previous page.
version: 0.16.6
homepage: https://github.com/blackmann/story_view

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  rxdart: ^0.28.0
  video_player: ^2.10.0
  collection: ^1.19.1
